apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: openshift-docker-runners
spec:
  # Using "HorizontalRunnerAutoscaler"
  # replicas: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      group: OpenShift
      labels:
        - docker,openshift
      organization: ${ORG_NAME}
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "250m"
          memory: "500Mi"
      image: ${PATH_TO_IMAGE}
      containers:
      - name: docker
        volumeMounts:
        - mountPath: /etc/docker/daemon.json
          name: daemon-json
          subPath: daemon.json
      volumes:
      - name: daemon-json
        configMap:
          name: daemon-json
