apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: openshift-podman-runner
spec:
  # Using "HorizontalRunnerAutoscaler"
  # replicas: 0
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      # Assign runner group
      dockerdWithinRunnerContainer: false #disable the docker container
      group: ${RUNNER_GROUP_NAME}
      labels:
        - podman
      organization: ${ORG}
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "250m"
          memory: "250Mi"
      image: ${PATH_TO_IMAGE}
      
      # Optionally break out the storage layer for podman,
      # handy for large builds that need persistant data 
      # between runners
#       containers:
#       - name: runner
#         volumeMounts:
#         - mountPath: /home/podman/.local/share/containers/storage 
#           name: podman-storage
#       volumes:
#       - name: podman-storage
#         persistentVolumeClaim: 
#           claimName: "podman-runner-pvc"

# ---
# apiVersion: "v1"
# kind: "PersistentVolumeClaim"
# metadata:
#   name: "podman-runner-pvc"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: "thin"
#   volumeMode: Filesystem
